version: "3.2"
services: 
    app:
        container_name: mvc-auth-demo
        build: .
        ports:
            - "8085:5001"
        depends_on: 
            - db     
    db:
        container_name: mssql-db
        build: mssql/.
        ports:
            - "1433:1433"
        environment:
            MSSSQL_PID: "Developer"
            MSSQL_USER: "SA"
            MSSQL_SA_PASSWORD: "MyPass@word"
            ACCEPT_EULA: "Y" 
